### ISSUE TITLE
I have a repo with 2 node projects, can i use this plugin for both projects?

### ISSUE THREAD

**Issue by franz-see** [IgnusG/jest-report-action#117]

**Comment by IgnusG** [comment]
Yes. You can setup your 2 test suites as 2 separate action steps and run this action after each one:
- run: npm run test-one
- use: jest-report-action
- run: npm run test-two
- use: jest-report-action

> Sorry for the delayed response

**Comment by elpddev** [comment]
Great repo. 

In my case, I'm using `yarn workspaces foreach run test` which does not specify each folder manually. 

So instead of specify jest-report-action multiple times, I use  [junit-report-merge](https://github.com/bhovhannes/junit-report-merger) to merge all reports into one and then use that report with the action.
