### ISSUE TITLE
Q: Why is .js file extension not supported?

### ISSUE THREAD

**Issue by ClydeDz** [IgnusG/jest-report-action#152]
Hi,

While trying to resolve #116, I got the following error. 

![2](https://user-images.githubusercontent.com/13506613/111285169-b9364700-86a5-11eb-93f2-715e8aab1250.png)

I had a [look at the code](https://github.com/IgnusG/jest-report-action/blob/c006b890ba3c3b650e6c55916a643ca82b64133b/tasks/js-parser.js#L72-L74) and noticed `.js` file extension is missing from the list. I updated mine to `.jsx` and it worked well.

Why is `.js` file extension not valid though? The create-react-app (for instance) comes with all JS files for code and test, so it's definitely a valid test file. 

Thanks!

**Comment by IgnusG** [comment]
Hi @ClydeDz! JS is supported out of the box. The list you found is meant to add support for additional languages through plugins (since normal JS doesn't need a plugin it's not listed there).

If you got an error and changing the extension helped, it probably means there's some syntax that Babel (the parser I'm using) doesn't understand inside a regular JS file but does so in JSX. 

Can you share the contents of the file you're getting the error for?

**Comment by ClydeDz** [comment]
Hi Jonathan,

Thanks for the quick response. Sure, [this is the commit](https://github.com/ClydeDz/github-actions-demo/commit/cce77ec42fe26d1c0b2fedb74321c884ce64ee3c) that renames the file and [this is the JS file](https://github.com/ClydeDz/github-actions-demo/blob/41e0537f006e9e1a428e23574300110f6945f14e/src/App.test.js) before renaming - contents are still the same though.

**Comment by IgnusG** [comment]
Hi @ClydeDz. Yeah it's as I suspected, on this line
https://github.com/ClydeDz/github-actions-demo/blob/41e0537f006e9e1a428e23574300110f6945f14e/src/App.test.js#L16
and others you have jsx syntax (`<Component />`). 

Since this action only activates the jsx plugin when it sees the `.jsx` extension it fails to understand it here. Changing the extension tells it that it should expect such syntax in this file.

You can find an interesting discussion about the reasoning behind using the extension `.jsx` for this syntax here https://github.com/airbnb/javascript/pull/985

Sorry about that! Hope it helps though

**Comment by ClydeDz** [comment]
Hi Jonathan, yes, that helps. Thanks for clarifying!
