### ISSUE TITLE
Creating another action named (Unnamed event) (Unnamed workflow): by ghost

### ISSUE THREAD

**Issue by fahadshehzada** [IgnusG/jest-report-action#33]
Hi, 
this solution seems worked for me but the issue facing in my gihub action is it creates a separate action as comment on test failure instead on the same PR result named ghost

![image](https://user-images.githubusercontent.com/61680750/83794610-ad017000-a6b7-11ea-881b-2330291f17a4.png)

![image](https://user-images.githubusercontent.com/61680750/83794659-c0144000-a6b7-11ea-81d5-c377c7d69f65.png)

.yml file

![image](https://user-images.githubusercontent.com/61680750/83794912-213c1380-a6b8-11ea-8557-4d38038c0b6f.png)

**Comment by fahadshehzada** [comment]
name: Pull Requests CI

on: [pull_request]

jobs:
   test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [
          ### All services goes here
        ]

    steps:
      - name: Check if service has changed
        uses: actions/github-script@0.9.0
        id: service-changed
        with:
          result-encoding: string
          script: |
            ### Logic part here
            
      - uses: actions/checkout@v2
         ### Logic part here
      
      - name: Setup Node
         ### Logic part here
          
      - name: Login to npm repo
         ### Logic part here

      - name: Yarn Install
         ### Logic part here

      - name: Lint and Prettify
         ### Logic part here

      - name: Build
         ### Logic part here
      
      - name: Yarn Test
        ### Logic part here

      - name: Yarn E2E
        ### Logic part here

      - name: Jest Github Action Reporter
        uses: IgnusG/jest-report-action@v2.3.2
        if: ${{ steps.service-changed.outputs.result == 'true' && (success() || steps.unit-test.outcome == 'failure' || steps.e2e-test.outcome == 'failure') }}
        with:
          working-directory: ${{ matrix.service.dir }}
          access-token: ${{ secrets.GITHUB_TOKEN }}
          run-name: test
          check-name: Test

**Comment by IgnusG** [comment]
This might be related to https://github.com/vegaprotocol/jest-report-action/commit/868e5c96f178e383c27bfa3e87c1c1b847c0b0b1#commitcomment-38793947

Reference https://github.community/t/workflow-name-suddenly-unknown-event/18258

**Comment by fahadshehzada** [comment]
Seems related to that issue but it won't fix as per the suggestion mentioned in this

**Comment by dbalcomb** [comment]
Hi there, I don't use this action but it looks useful so I might try to incorporate it in to one of my projects.

I stumbled across @fahadshehzada post to the GitHub Support Community and thought I would check it out because I am aware of the issue as I have experienced it with another action that creates annotations. I am also aware of the fix.

So the problem is that a GitHub Actions workflow triggered on a pull request will run on an intermediate merge commit. In order to create the annotations you need to attach them to a check run which is created on a specific SHA. The reason you are seeing the unnamed workflow is that the merge commit SHA doesn't actually exist outside of the pull request workflow.

So to fix the issue you need to update [this line](https://github.com/IgnusG/jest-report-action/blob/dc1d6982fabb64ed20f3e69e71399f107237f73a/tasks/github-api.js#L9) and pass it the correct SHA.

You should be able to use something like the following to get the correct SHA in a pull request workflow.

```js
let sha = github.context.sha

if (github.context.payload.pull_request) {
    sha = github.context.payload.pull_request.head.sha
}
```

You can see a pull request I made to another GitHub Action [here](https://github.com/actions-rs/clippy-check/pull/65).

**Comment by IgnusG** [comment]
Thanks @dbalcomb for the suggestion! I'll ty it out and release a fix as soon as possible

**Comment by IgnusG** [comment]
@fahadshehzada Can you check if https://github.com/IgnusG/jest-report-action/releases/tag/v2.3.3 resolved your issue?

**Comment by fahadshehzada** [comment]
Thanks for the fix @dbalcomb. Tried your solution it works for me.
Thanks @IgnusG for adding this and provide the release version. It will help for everyone
